group 'com.appspector.flutter'
version '1.0'

buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        maven { url "https://maven.appspector.com/artifactory/android-sdk" }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion = 35

    if (project.android.hasProperty('namespace')) {
        namespace "com.appspector.flutter"
    }


    defaultConfig {
        minSdkVersion 21
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation("com.appspector:android-sdk:1.5.+") {
        exclude group:"org.jetbrains.kotlin"
    }
    implementation 'androidx.annotation:annotation:1.6.0'
}
